version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS=127.0.0.1,localhost,0.0.0.0
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_data:/vol/static
    ports:
      - "8279:8279"
    depends_on:
      - app

  postgres:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw1234
      POSTGRES_DB: base123


volumes:
  static_data: